<<<<<<< HEAD
version: 2

models:
  - name: stg_sub
    columns:
      - name: submission_id
        tests:
          - not_null
          - unique
      - name: fiscal_period
        tests:
          - accepted_values:
              values: ["FY", "Q1", "Q2", "Q3", "Q4"]
      - name: company_id
        tests:
          - not_null
      - name: period
        tests:
          - not_null
      - name: filing_date
        tests:
          - not_null
  - name: stg_num
    columns:
      - name: submission_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_sub')
              field: submission_id
      - name: tag
        tests:
          - not_null
      - name: version
        tests:
          - not_null
  - name: stg_pre
    columns:
      - name: submission_id
        tests:
          - not_null
      - name: report
        tests:
          - not_null
      - name: line
        tests:
          - not_null
      - name: statement_type
        tests:
          - accepted_values:
              values: ["BS", "IS", "CF", "EQ", "CI", "SI", "UN", "CP"]
      - name: directly_reported
        tests:
          - accepted_values:
              values: [0, 1]
      - name: negating
        tests:
          - accepted_values:
              values: [0, 1]
  - name: stg_tag
    columns:
      - name: tag
        tests:
          - not_null
      - name: version
        tests:
          - not_null
      - name: custom
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: abstract
        tests:
          - accepted_values:
              values: [0, 1]
=======
version: 2

models:
  - name: stg_sub
    columns:
      - name: submission_id
        tests:
          - not_null
          - unique
      - name: fiscal_period
        tests:
          - accepted_values:
              values: ["FY", "Q1", "Q2", "Q3", "Q4"]
      - name: company_id
        tests:
          - not_null
      # - name: period
      #   tests:
      #     - not_null
      - name: filing_date
        tests:
          - not_null
  - name: stg_num
    columns:
      - name: submission_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_sub')
              field: submission_id
      - name: tag
        tests:
          - not_null
      - name: version
        tests:
          - not_null
  - name: stg_pre
    columns:
      - name: submission_id
        tests:
          - not_null
      - name: report
        tests:
          - not_null
      - name: line
        tests:
          - not_null
      - name: statement_type
        tests:
          - accepted_values:
              values: ["BS", "IS", "CF", "EQ", "CI", "SI", "UN", "CP"]
      - name: directly_reported
        tests:
          - accepted_values:
              values: [0, 1]
      - name: negating
        tests:
          - accepted_values:
              values: [0, 1]
  - name: stg_tag
    columns:
      - name: tag
        tests:
          - not_null
      - name: version
        tests:
          - not_null
      - name: custom
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: abstract
        tests:
          - accepted_values:
              values: [0, 1]
>>>>>>> origin/main
